// <auto-generated />
using System;
using MagicVilla.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MagicVilla.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20231203160258_createdDataTableVilla")]
    partial class createdDataTableVilla
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MagicVilla.Models.Villa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Detail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<string>("Province")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Villas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Capacity = 30,
                            DateCreated = new DateTime(2023, 12, 3, 13, 2, 58, 335, DateTimeKind.Local).AddTicks(9048),
                            DateUpdated = new DateTime(2023, 12, 3, 13, 2, 58, 335, DateTimeKind.Local).AddTicks(9061),
                            Detail = "first villa created",
                            ImageUrl = "",
                            Name = "First Villa",
                            Price = 550.0,
                            Province = "Cordoba"
                        },
                        new
                        {
                            Id = 2,
                            Capacity = 60,
                            DateCreated = new DateTime(2023, 12, 3, 13, 2, 58, 335, DateTimeKind.Local).AddTicks(9064),
                            DateUpdated = new DateTime(2023, 12, 3, 13, 2, 58, 335, DateTimeKind.Local).AddTicks(9065),
                            Detail = "second villa created",
                            ImageUrl = "",
                            Name = "Second Villa",
                            Price = 350.0,
                            Province = "Mendoza"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
